version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - ENVIRONMENT=production
      # Adicione outras variáveis de ambiente necessárias
    ports:
      - "80:8000"
    # Volumes removidos para produção

  # Serviços configurados para produção
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Apenas exponha esta porta se precisar acessar remotamente
    # ports:
    #   - "5432:5432"

volumes:
  postgres_data: